const fs = require('node:fs');
const path = require('node:path');
const file = path.resolve(__dirname, '../lib/l10n/app_localizations_all.dart');
const codes = ['fr', 'es', 'it', 'pt', 'nl', 'pl', 'ar', 'fa', 'ckb', 'ja', 'zh', 'hi'];
const rows = `
event_host|Hôte|Anfitrión|Organizzatore|Anfitrião|Organisator|Organizator|المضيف|میزبان|خانەخوێ|主催者|组织者|मेज़बान
event_shared_by|Partagé par|Compartido por|Condiviso da|Partilhado por|Gedeeld door|Udostępnione przez|شاركه|اشتراک‌گذاری توسط|بڵاوکراوەتەوە لەلایەن|共有した人|分享者|साझा करने वाले
event_deleted|Événement supprimé.|Evento eliminado.|Evento eliminato.|Evento eliminado.|Evenement verwijderd.|Wydarzenie usunięte.|تم حذف الفعالية.|رویداد حذف شد.|بۆنەکە سڕایەوە.|イベントを削除しました。|活动已删除。|कार्यक्रम हटा दिया गया।
event_visibility_public|Public (visible à proximité)|Público (visible cerca)|Pubblico (visibile nelle vicinanze)|Público (visível nas proximidades)|Openbaar (zichtbaar in de buurt)|Publiczne (widoczne w pobliżu)|عام (مرئي بالقرب منك)|عمومی (قابل مشاهده در نزدیکی)|گشتی (لە نزیکت دەبینرێت)|公開（近くの人に表示）|公开（附近可见）|सार्वजनिक (आसपास दिखाई देगा)
event_visibility_circle|Cercle familial (visible par vos contacts)|Círculo familiar (visible para tus contactos)|Cerchia familiare (visibile ai tuoi contatti)|Círculo familiar (visível aos seus contactos)|Familiekring (zichtbaar voor je contacten)|Krąg rodzinny (widoczne dla kontaktów)|دائرة العائلة (مرئي لجهات اتصالك)|حلقه خانواده (قابل مشاهده برای مخاطبان)|بازنەی خێزان (پەیوەندییەکانت دەیبینن)|家族の輪（連絡先に表示）|家庭圈（联系人可见）|परिवार का समूह (संपर्कों को दिखाई देगा)
event_open_website|Ouvrir le site de l'événement|Abrir la web del evento|Apri il sito dell'evento|Abrir o site do evento|Website van het evenement openen|Otwórz stronę wydarzenia|فتح موقع الفعالية|باز کردن وب‌سایت رویداد|ماڵپەڕی بۆنەکە بکەرەوە|イベントのサイトを開く|打开活动网站|कार्यक्रम की वेबसाइट खोलें
events_gps_unavailable|GPS indisponible. Saisissez un lieu ci-dessus.|GPS no disponible. Introduce un lugar arriba.|GPS non disponibile. Inserisci un luogo sopra.|GPS indisponível. Introduza um local acima.|GPS niet beschikbaar. Vul hierboven een locatie in.|GPS niedostępny. Wpisz lokalizację powyżej.|الموقع غير متاح. أدخل مكانًا أعلاه.|موقعیت‌یابی در دسترس نیست. مکان را در بالا وارد کنید.|شوێنیابی بەردەست نییە. لە سەرەوە شوێنێک بنووسە.|位置情報を取得できません。上に場所を入力してください。|定位不可用，请在上方输入地点。|स्थान उपलब्ध नहीं है। ऊपर स्थान दर्ज करें।
events_my_location|Ma position|Mi ubicación|La mia posizione|A minha localização|Mijn locatie|Moja lokalizacja|موقعي|موقعیت من|شوێنی من|自分の位置|我的位置|मेरा स्थान
events_current_location|Position actuelle|Ubicación actual|Posizione attuale|Localização atual|Huidige locatie|Bieżąca lokalizacja|الموقع الحالي|موقعیت فعلی|شوێنی ئێستا|現在地|当前位置|वर्तमान स्थान
events_age_infant|0–1 an|0–1 años|0–1 anni|0–1 anos|0–1 jaar|0–1 lat|٠–١ سنة|۰–۱ سال|٠–١ ساڵ|0～1歳|0–1岁|0–1 वर्ष
events_age_toddler|1–3 ans|1–3 años|1–3 anni|1–3 anos|1–3 jaar|1–3 lata|١–٣ سنوات|۱–۳ سال|١–٣ ساڵ|1～3歳|1–3岁|1–3 वर्ष
events_age_preschool|4–6 ans|4–6 años|4–6 anni|4–6 anos|4–6 jaar|4–6 lat|٤–٦ سنوات|۴–۶ سال|٤–٦ ساڵ|4～6歳|4–6岁|4–6 वर्ष
events_age_elementary|6–10 ans|6–10 años|6–10 anni|6–10 anos|6–10 jaar|6–10 lat|٦–١٠ سنوات|۶–۱۰ سال|٦–١٠ ساڵ|6～10歳|6–10岁|6–10 वर्ष
events_age_teenager|11–16 ans|11–16 años|11–16 anni|11–16 anos|11–16 jaar|11–16 lat|١١–١٦ سنة|۱۱–۱۶ سال|١١–١٦ ساڵ|11～16歳|11–16岁|11–16 वर्ष
events_age_mixed|Âges variés|Edades mixtas|Età miste|Várias idades|Gemengde leeftijden|Różne grupy wiekowe|أعمار مختلطة|سنین مختلف|تەمەنی جیاواز|幅広い年齢|混合年龄|अलग-अलग उम्र
events_invitation_pending|En attente|Pendiente|In attesa|Pendente|In afwachting|Oczekująca|قيد الانتظار|در انتظار|چاوەڕوان|保留中|待处理|लंबित
events_invitation_accepted|Acceptée|Aceptada|Accettato|Aceite|Geaccepteerd|Przyjęta|مقبولة|پذیرفته شده|پەسەندکراو|承諾済み|已接受|स्वीकार किया गया
events_invitation_declined|Refusée|Rechazada|Rifiutato|Recusado|Afgewezen|Odrzucona|مرفوضة|رد شده|ڕەتکراوە|辞退済み|已拒绝|अस्वीकार किया गया
events_invitation_fallback_title|Événement {id}|Evento {id}|Evento {id}|Evento {id}|Evenement {id}|Wydarzenie {id}|فعالية {id}|رویداد {id}|بۆنەی {id}|イベント {id}|活动 {id}|कार्यक्रम {id}
events_without_id|sans identifiant|sin identificador|senza identificativo|sem identificador|zonder identificatie|bez identyfikatora|بلا معرّف|بدون شناسه|بێ ناسێنەر|識別番号なし|无编号|बिना पहचान संख्या
events_invitation_accept_success|Invitation acceptée.|Invitación aceptada.|Invito accettato.|Convite aceite.|Uitnodiging geaccepteerd.|Zaproszenie przyjęte.|تم قبول الدعوة.|دعوت پذیرفته شد.|بانگهێشتەکە پەسەندکرا.|招待を承諾しました。|已接受邀请。|निमंत्रण स्वीकार किया गया।
events_invitation_decline_success|Invitation refusée.|Invitación rechazada.|Invito rifiutato.|Convite recusado.|Uitnodiging afgewezen.|Zaproszenie odrzucone.|تم رفض الدعوة.|دعوت رد شد.|بانگهێشتەکە ڕەتکرایەوە.|招待を辞退しました。|已拒绝邀请。|निमंत्रण अस्वीकार किया गया।
events_last_sync|Événements actualisés : {time}|Eventos actualizados: {time}|Eventi aggiornati: {time}|Eventos atualizados: {time}|Evenementen bijgewerkt: {time}|Wydarzenia zaktualizowane: {time}|تحديث الفعاليات: {time}|رویدادها به‌روز شدند: {time}|بۆنەکان نوێکرانەوە: {time}|更新日時：{time}|活动更新于：{time}|कार्यक्रम अपडेट किए गए: {time}
events_nearby_for_you|Près de vous|Cerca de ti|Vicino a te|Perto de si|Bij jou in de buurt|W pobliżu|بالقرب منك|نزدیک شما|لە نزیکت|近く|在你附近|आपके पास
events_family_spot_title|Votre coin famille|Tu espacio familiar|Il vostro spazio famiglia|O seu espaço familiar|Jouw familieplek|Wasze miejsce rodzinne|مساحتك العائلية|فضای خانوادگی شما|شوێنی خێزانەکەت|家族の場所|你的家庭空间|आपके परिवार की जगह
events_family_spot_subtitle|Découvrir. Partager. Vivre ensemble.|Descubrir. Compartir. Disfrutar juntos.|Scoprire. Condividere. Vivere insieme.|Descobrir. Partilhar. Viver juntos.|Ontdekken. Delen. Samen beleven.|Odkrywaj. Dziel się. Przeżywaj razem.|اكتشف. شارك. استمتعوا معًا.|کشف کنید. به اشتراک بگذارید. با هم تجربه کنید.|بدۆزەرەوە. هاوبەشی بکە. پێکەوە ئەزموون بکەن.|発見。共有。一緒に体験。|发现。分享。共同体验。|खोजें। साझा करें। साथ अनुभव करें।
events_plan_event|Planifier un événement|Planear un evento|Organizza un evento|Planear um evento|Evenement plannen|Zaplanuj wydarzenie|تخطيط فعالية|برنامه‌ریزی رویداد|بۆنەیەک پلان بکە|イベントを計画|筹划活动|कार्यक्रम की योजना बनाएँ
events_invitations|Invitations|Invitaciones|Inviti|Convites|Uitnodigingen|Zaproszenia|الدعوات|دعوت‌ها|بانگهێشتەکان|招待|邀请|निमंत्रण
events_choose_location|Choisir un lieu|Elegir lugar|Scegli luogo|Escolher local|Locatie kiezen|Wybierz lokalizację|اختيار مكان|انتخاب مکان|شوێن هەڵبژێرە|場所を選択|选择地点|स्थान चुनें
events_gps_active|GPS actif|GPS activo|GPS attivo|GPS ativo|GPS actief|GPS aktywny|تحديد الموقع نشط|موقعیت‌یابی فعال است|شوێنیابی چالاکە|位置情報有効|定位已开启|स्थान सेवा चालू है
events_detect_location|Détecter automatiquement le lieu|Detectar ubicación automáticamente|Rileva posizione automaticamente|Detetar localização automaticamente|Locatie automatisch bepalen|Wykryj lokalizację automatycznie|تحديد الموقع تلقائيًا|تشخیص خودکار مکان|شوێن بە خۆکار بدۆزەرەوە|場所を自動取得|自动检测位置|स्थान अपने आप खोजें
events_nearby_only|À proximité uniquement ({count})|Solo cerca ({count})|Solo nelle vicinanze ({count})|Só nas proximidades ({count})|Alleen dichtbij ({count})|Tylko w pobliżu ({count})|بالقرب فقط ({count})|فقط نزدیک ({count})|تەنها نزیک ({count})|近くのみ（{count}）|仅附近（{count}）|केवल आसपास ({count})
events_filter_title|Filtres et classement|Filtros y orden|Filtri e ordinamento|Filtros e ordenação|Filters en volgorde|Filtry i kolejność|التصفية والترتيب|فیلترها و رتبه‌بندی|پاڵاوتن و ڕیزبەندی|絞り込みと並び順|筛选与排序|फ़िल्टर और क्रम
events_sort_explanation|Tri par distance, date et âge adapté.|Ordenados por distancia, fecha y edad adecuada.|Ordinati per distanza, data e fascia d'età.|Ordenados por distância, data e faixa etária.|Gesorteerd op afstand, tijd en passende leeftijd.|Kolejność według odległości, terminu i wieku.|مرتبة حسب المسافة والموعد والفئة العمرية.|مرتب‌شده بر اساس فاصله، زمان و گروه سنی.|بەپێی دووری، کات و تەمەنی گونجاو ڕیزکراون.|距離、日時、対象年齢で並べています。|按距离、时间及适合年龄排序。|दूरी, समय और उपयुक्त उम्र के आधार पर क्रम।
events_open_count|{count} en attente|{count} pendientes|{count} in sospeso|{count} pendentes|{count} openstaand|{count} oczekujących|{count} معلقة|{count} باز|{count} چاوەڕوان|{count}件未処理|{count}个待处理|{count} लंबित
events_no_open_invitations|Aucune invitation en attente.|No hay invitaciones pendientes.|Nessun invito in sospeso.|Sem convites pendentes.|Geen openstaande uitnodigingen.|Brak oczekujących zaproszeń.|لا توجد دعوات معلقة.|دعوت بازی وجود ندارد.|هیچ بانگهێشتێکی چاوەڕوان نییە.|未処理の招待はありません。|没有待处理的邀请。|कोई लंबित निमंत्रण नहीं।
events_invitation_from|De {host} · Reçue : {date}|De {host} · Recibida: {date}|Da {host} · Ricevuto: {date}|De {host} · Recebido: {date}|Van {host} · Ontvangen: {date}|Od {host} · Otrzymano: {date}|من {host} · استُلمت: {date}|از {host} · دریافت: {date}|لە {host} · گەیشتووە: {date}|{host}から · 受信：{date}|来自{host} · 收到：{date}|{host} से · प्राप्त: {date}
events_accept_invitation|Accepter|Aceptar|Accetta|Aceitar|Accepteren|Przyjmij|قبول|پذیرفتن|پەسەندکردن|承諾|接受|स्वीकार करें
events_distance_near|proche|cerca|vicino|perto|dichtbij|blisko|قريب|نزدیک|نزیک|近い|近|पास
events_distance_medium|moyenne|media|media|média|gemiddeld|średnio|متوسط|متوسط|مامناوەند|中距離|中等|मध्यम
events_distance_far|loin|lejos|lontano|longe|ver weg|daleko|بعيد|دور|دوور|遠い|远|दूर
events_source_ai|IA|IA|IA|IA|KI|SI|ذكاء اصطناعي|هوش مصنوعی|زیرەکی دەستکرد|人工知能|人工智能|कृत्रिम बुद्धिमत्ता
events_source_community|Communauté|Comunidad|Comunità|Comunidade|Gemeenschap|Społeczność|المجتمع|جامعه|کۆمەڵگا|コミュニティ|社区|समुदाय
events_price_label|Prix : {price}|Precio: {price}|Prezzo: {price}|Preço: {price}|Prijs: {price}|Cena: {price}|السعر: {price}|قیمت: {price}|نرخ: {price}|料金：{price}|价格：{price}|मूल्य: {price}
events_for_age|Pour : {age}|Para: {age}|Per: {age}|Para: {age}|Voor: {age}|Dla: {age}|لأعمار: {age}|برای: {age}|بۆ: {age}|対象：{age}|适合：{age}|इनके लिए: {age}
event_discover_title|Découvrir des activités|Descubrir actividades|Scopri attività|Descobrir atividades|Activiteiten ontdekken|Odkryj aktywności|اكتشاف الأنشطة|کشف فعالیت‌ها|چالاکی بدۆزەرەوە|アクティビティを探す|探索活动|गतिविधियाँ खोजें
event_places|Places|Plazas|Posti|Vagas|Plaatsen|Miejsca|الأماكن|ظرفیت|شوێنەکان|定員|名额|स्थान
event_detail_sign_in_required|Connectez-vous pour participer aux événements.|Inicia sesión para participar en eventos.|Accedi per partecipare agli eventi.|Inicie sessão para participar nos eventos.|Log in om aan evenementen deel te nemen.|Zaloguj się, aby uczestniczyć w wydarzeniach.|سجّل الدخول للمشاركة في الفعاليات.|برای شرکت در رویدادها وارد شوید.|بۆ بەشداری لە بۆنەکان بچۆ ژوورەوە.|参加するにはログインしてください。|请登录后参加活动。|कार्यक्रमों में भाग लेने के लिए लॉग इन करें।
event_detail_request_sent|Demande de participation envoyée !|¡Solicitud de participación enviada!|Richiesta di partecipazione inviata!|Pedido de participação enviado!|Deelnameverzoek verstuurd!|Prośba o udział wysłana!|تم إرسال طلب المشاركة!|درخواست شرکت ارسال شد!|داوای بەشداری نێردرا!|参加申請を送信しました。|参加申请已发送！|भाग लेने का अनुरोध भेजा गया!
event_detail_error|Erreur : {error}|Error: {error}|Errore: {error}|Erro: {error}|Fout: {error}|Błąd: {error}|خطأ: {error}|خطا: {error}|هەڵە: {error}|エラー：{error}|错误：{error}|त्रुटि: {error}
event_detail_participants|{current}/{maximum} participants|{current}/{maximum} participantes|{current}/{maximum} partecipanti|{current}/{maximum} participantes|{current}/{maximum} deelnemers|{current}/{maximum} uczestników|{current}/{maximum} مشاركين|{current}/{maximum} شرکت‌کننده|{current}/{maximum} بەشداربوو|参加者 {current}/{maximum}人|参加人数 {current}/{maximum}|{current}/{maximum} प्रतिभागी
event_detail_spots_available|{count} places disponibles|{count} plazas disponibles|{count} posti disponibili|{count} vagas disponíveis|{count} plaatsen beschikbaar|{count} wolnych miejsc|{count} أماكن متاحة|{count} جای خالی|{count} شوێنی بەتاڵ|空き {count}人分|剩余{count}个名额|{count} स्थान उपलब्ध
event_detail_fully_booked|Complet|Completo|Al completo|Lotado|Volgeboekt|Brak wolnych miejsc|مكتمل العدد|ظرفیت تکمیل است|شوێنەکان پڕ بوون|満員|已满额|सभी स्थान भर गए
event_detail_description|Description|Descripción|Descrizione|Descrição|Beschrijving|Opis|الوصف|توضیحات|وەسف|説明|说明|विवरण
event_owner_yours|Votre événement|Tu evento|Il tuo evento|O seu evento|Jouw evenement|Twoje wydarzenie|فعاليتك|رویداد شما|بۆنەکەی تۆ|自分のイベント|你的活动|आपका कार्यक्रम
event_mode_label|Participation|Participación|Partecipazione|Participação|Deelname|Udział|المشاركة|شرکت|بەشداری|参加方法|参与方式|भागीदारी
event_mode_legacyApproval|Avec accord de l'hôte|Con aprobación del anfitrión|Con approvazione dell'organizzatore|Com aprovação do anfitrião|Met toestemming van de organisator|Za zgodą organizatora|بموافقة المضيف|با تأیید میزبان|بە پەسەندکردنی خانەخوێ|主催者の承認|组织者批准|मेज़बान की स्वीकृति से
event_mode_direct|Organiser une rencontre|Organizar un encuentro|Organizza un incontro|Organizar um encontro|Een bijeenkomst organiseren|Zorganizuj spotkanie|تنظيم لقاء|برگزاری دورهمی|دیدارێک ڕێک بخە|集まりを主催|组织聚会|मिलन आयोजित करें
event_mode_interest|Partager une offre|Compartir una propuesta|Condividi una proposta|Partilhar uma oferta|Een aanbod delen|Udostępnij ofertę|مشاركة عرض|اشتراک‌گذاری پیشنهاد|پێشنیارێک بڵاو بکەرەوە|企画を共有|分享活动信息|प्रस्ताव साझा करें
event_direct_confirmation|Inscription directe avec une place confirmée.|Inscripción directa con plaza confirmada.|Iscrizione diretta con posto confermato.|Inscrição direta com vaga confirmada.|Direct aanmelden met een bevestigde plaats.|Bezpośredni zapis z potwierdzonym miejscem.|تسجيل مباشر مع مكان مؤكد.|ثبت‌نام مستقیم با جای تأییدشده.|تۆمارکردنی ڕاستەوخۆ بە شوێنی پشتڕاستکراو.|直接申し込みで参加枠が確定します。|直接报名，名额已确认。|सीधे पंजीकरण से स्थान की पुष्टि होती है।
event_interest_not_booking|Offre publique partagée. L'intérêt ne vaut pas réservation ; inscrivez-vous auprès de l'organisateur.|Oferta pública compartida. El interés no es una reserva; inscríbete con el organizador.|Proposta pubblica condivisa. L'interesse non è una prenotazione; iscriviti presso l'organizzatore.|Oferta pública partilhada. O interesse não é uma reserva; inscreva-se junto do organizador.|Gedeeld openbaar aanbod. Interesse is geen reservering; meld je aan bij de organisator.|Udostępniona oferta publiczna. Zainteresowanie nie jest rezerwacją; zapisz się u organizatora.|عرض عام مشترك. الاهتمام ليس حجزًا؛ سجّل لدى المنظم.|پیشنهاد عمومی به اشتراک گذاشته شده. علاقه‌مندی رزرو نیست؛ نزد برگزارکننده ثبت‌نام کنید.|پێشنیاری گشتی بڵاوکراوەتەوە. حەزکردن حجز نییە؛ لای ڕێکخەر تۆمار بکە.|共有された公開企画です。興味の表明は予約ではありません。主催者に申し込んでください。|分享的公开活动。感兴趣不等于预订，请向组织者报名。|साझा किया गया सार्वजनिक प्रस्ताव। रुचि जताना बुकिंग नहीं है; आयोजक के पास पंजीकरण करें।
event_organizer_url|Lien de l'organisateur|Enlace del organizador|Link dell'organizzatore|Ligação do organizador|Link van de organisator|Link organizatora|رابط المنظم|پیوند برگزارکننده|بەستەری ڕێکخەر|主催者のリンク|组织者链接|आयोजक का लिंक
event_invalid_url|Saisissez un lien http ou https valide.|Introduce un enlace http o https válido.|Inserisci un link http o https valido.|Introduza uma ligação http ou https válida.|Vul een geldige http- of https-link in.|Podaj poprawny link http lub https.|أدخل رابط http أو https صالحًا.|پیوند معتبر http یا https وارد کنید.|بەستەرێکی دروستی http یان https بنووسە.|有効なhttpまたはhttpsのリンクを入力してください。|请输入有效的http或https链接。|मान्य http या https लिंक दर्ज करें।
event_open_organizer|Voir l'organisateur|Visitar al organizador|Visita l'organizzatore|Visitar o organizador|Naar de organisator|Przejdź do organizatora|زيارة المنظم|مشاهده برگزارکننده|سەردانی ڕێکخەر بکە|主催者のサイトへ|访问组织者|आयोजक की वेबसाइट खोलें
event_join_direct|Participer à la rencontre|Unirse al encuentro|Partecipa all'incontro|Participar no encontro|Meedoen aan de bijeenkomst|Dołącz do spotkania|الانضمام للقاء|شرکت در دورهمی|بەشداری دیدار بکە|集まりに参加|参加聚会|मिलन में भाग लें
event_show_interest|Intéressé|Me interesa|Mi interessa|Tenho interesse|Ik heb interesse|Interesuje mnie|مهتم|علاقه‌مندم|حەزم لێیە|興味あり|感兴趣|रुचि है
event_interest_saved|Votre intérêt est enregistré. Aucune place réservée.|Interés guardado. No hay plaza reservada.|Interesse salvato. Nessun posto prenotato.|Interesse guardado. Nenhuma vaga reservada.|Je interesse is opgeslagen. Geen plaats gereserveerd.|Zainteresowanie zapisane. Nie zarezerwowano miejsca.|تم حفظ اهتمامك. لم يُحجز مكان.|علاقه‌مندی ثبت شد. جایی رزرو نشده است.|حەزکردنت تۆمارکرا. هیچ شوێنێک حجز نەکراوە.|興味を保存しました。参加枠は予約されていません。|已保存兴趣，未预留名额。|रुचि दर्ज हुई। कोई स्थान आरक्षित नहीं है।
event_interest_withdraw|Retirer mon intérêt|Quitar interés|Rimuovi interesse|Retirar interesse|Interesse intrekken|Usuń zainteresowanie|إلغاء الاهتمام|حذف علاقه‌مندی|حەزکردن بسڕەوە|興味を取り消す|取消兴趣|रुचि हटाएँ
event_withdraw|Annuler ma participation|Retirar participación|Annulla partecipazione|Cancelar participação|Deelname intrekken|Wycofaj udział|إلغاء المشاركة|لغو شرکت|بەشداری هەڵبوەشێنەوە|参加を取り消す|取消参加|भागीदारी वापस लें
event_legacy_pending|En attente de l'accord de l'hôte. Aucune place confirmée.|Esperando la aprobación del anfitrión. Plaza aún no confirmada.|In attesa dell'organizzatore. Posto non ancora confermato.|À espera do anfitrião. Vaga ainda não confirmada.|Wacht op de organisator. Nog geen bevestigde plaats.|Oczekiwanie na organizatora. Miejsce nie jest potwierdzone.|بانتظار موافقة المضيف. لا يوجد مكان مؤكد بعد.|در انتظار تأیید میزبان. هنوز جایی تأیید نشده است.|چاوەڕێی پەسەندکردنی خانەخوێ. هێشتا شوێن پشتڕاست نەکراوە.|主催者の承認待ちです。参加枠は未確定です。|等待组织者确认，名额尚未确认。|मेज़बान की पुष्टि का इंतज़ार है। स्थान अभी पक्का नहीं है।
event_pending_preserved|Les demandes existantes restent en attente, sans approbation automatique.|Las solicitudes existentes siguen pendientes, sin aprobación automática.|Le richieste esistenti restano in attesa, senza approvazione automatica.|Os pedidos existentes continuam pendentes, sem aprovação automática.|Bestaande verzoeken blijven in afwachting en worden nooit automatisch goedgekeurd.|Obecne prośby pozostają oczekujące i nie są automatycznie zatwierdzane.|تبقى الطلبات الحالية معلقة ولا تُقبل تلقائيًا.|درخواست‌های موجود در انتظار می‌مانند و خودکار تأیید نمی‌شوند.|داواکارییەکانی ئێستا چاوەڕوان دەمێنن و بە خۆکار پەسەند ناکرێن.|既存の申請は保留のままで、自動承認されません。|现有申请仍待确认，不会自动批准。|मौजूदा अनुरोध लंबित रहेंगे और अपने आप स्वीकृत नहीं होंगे।
event_shared_by_you|Partagé par vous|Compartido por ti|Condiviso da te|Partilhado por si|Door jou gedeeld|Udostępnione przez Ciebie|شاركته أنت|شما به اشتراک گذاشته‌اید|تۆ بڵاوت کردووەتەوە|自分が共有|你分享的|आपके द्वारा साझा किया गया
event_status_failed|Impossible de charger votre statut de participation.|No se pudo cargar tu estado de participación.|Impossibile caricare lo stato di partecipazione.|Não foi possível carregar o estado da participação.|Je deelnamestatus kon niet worden geladen.|Nie udało się wczytać statusu udziału.|تعذّر تحميل حالة مشاركتك.|وضعیت شرکت شما بارگیری نشد.|دۆخی بەشدارییەکەت بار نەکرا.|参加状況を読み込めませんでした。|无法加载你的参与状态。|आपकी भागीदारी की स्थिति लोड नहीं हुई।
event_action_failed|Non enregistré. Réessayez.|No se guardó. Inténtalo de nuevo.|Non salvato. Riprova.|Não guardado. Tente novamente.|Niet opgeslagen. Probeer opnieuw.|Nie zapisano. Spróbuj ponownie.|لم يُحفظ. حاول مجددًا.|ذخیره نشد. دوباره تلاش کنید.|پاشەکەوت نەکرا. دووبارە هەوڵ بدە.|保存できませんでした。再試行してください。|未保存，请重试。|सहेजा नहीं गया। फिर प्रयास करें।
event_retry|Réessayer|Reintentar|Riprova|Tentar novamente|Opnieuw proberen|Spróbuj ponownie|إعادة المحاولة|تلاش دوباره|دووبارە هەوڵ بدە|再試行|重试|फिर प्रयास करें
event_closed|Participation close|Participación cerrada|Partecipazione chiusa|Participação encerrada|Deelname gesloten|Zapisy zamknięte|المشاركة مغلقة|ثبت‌نام بسته است|بەشداری داخراوە|参加受付終了|报名已关闭|भागीदारी बंद है
event_confirmed_count|{count} confirmés|{count} confirmados|{count} confermati|{count} confirmados|{count} bevestigd|{count} potwierdzonych|{count} مؤكدين|{count} تأییدشده|{count} پشتڕاستکراو|{count}人確定|已确认{count}人|{count} की पुष्टि हुई
event_owner_edit|Modifier|Editar|Modifica|Editar|Bewerken|Edytuj|تعديل|ویرایش|دەستکاری|編集|编辑|संपादित करें
event_owner_actions|Gérer l'événement|Gestionar evento|Gestisci evento|Gerir evento|Evenement beheren|Zarządzaj wydarzeniem|إدارة الفعالية|مدیریت رویداد|بۆنەکە بەڕێوە ببە|イベントを管理|管理活动|कार्यक्रम प्रबंधित करें
event_owner_edit_title|Modifier l'événement|Editar evento|Modifica evento|Editar evento|Evenement bewerken|Edytuj wydarzenie|تعديل الفعالية|ویرایش رویداد|بۆنەکە دەستکاری بکە|イベントを編集|编辑活动|कार्यक्रम संपादित करें
event_owner_title|Titre|Título|Titolo|Título|Titel|Tytuł|العنوان|عنوان|ناونیشان|タイトル|标题|शीर्षक
event_owner_location|Lieu|Lugar|Luogo|Local|Locatie|Lokalizacja|المكان|مکان|شوێن|場所|地点|स्थान
event_owner_capacity|Nombre maximal de participants|Máximo de participantes|Numero massimo di partecipanti|Máximo de participantes|Maximum aantal deelnemers|Maksymalna liczba uczestników|الحد الأقصى للمشاركين|حداکثر شرکت‌کنندگان|زۆرترین بەشداربوو|参加人数の上限|人数上限|अधिकतम प्रतिभागी
event_owner_capacity_min|Au moins {count} participants.|Al menos {count} participantes.|Almeno {count} partecipanti.|Pelo menos {count} participantes.|Minstens {count} deelnemers.|Co najmniej {count} uczestników.|على الأقل {count} مشاركين.|حداقل {count} شرکت‌کننده.|لانیکەم {count} بەشداربوو.|最低{count}人にしてください。|至少{count}名参加者。|कम से कम {count} प्रतिभागी।
event_owner_required|Veuillez remplir ce champ.|Rellena este campo.|Compila questo campo.|Preencha este campo.|Vul dit veld in.|Wypełnij to pole.|يرجى ملء هذا الحقل.|این قسمت را تکمیل کنید.|ئەم خانەیە پڕ بکەرەوە.|この項目を入力してください。|请填写此字段。|यह फ़ील्ड भरें।
event_owner_future_date|Choisissez une date et une heure futures.|Elige una fecha y hora futuras.|Scegli una data e un'ora future.|Escolha uma data e hora futuras.|Kies een datum en tijd in de toekomst.|Wybierz przyszłą datę i godzinę.|اختر تاريخًا ووقتًا في المستقبل.|تاریخ و زمان آینده را انتخاب کنید.|بەروار و کاتێکی داهاتوو هەڵبژێرە.|未来の日時を選んでください。|请选择未来的日期和时间。|आने वाली तारीख और समय चुनें।
event_owner_save|Enregistrer les modifications|Guardar cambios|Salva modifiche|Guardar alterações|Wijzigingen opslaan|Zapisz zmiany|حفظ التغييرات|ذخیره تغییرات|گۆڕانکارییەکان پاشەکەوت بکە|変更を保存|保存更改|बदलाव सहेजें
event_owner_saved|Votre événement a été mis à jour.|Tu evento se ha actualizado.|Il tuo evento è stato aggiornato.|O seu evento foi atualizado.|Je evenement is bijgewerkt.|Twoje wydarzenie zostało zaktualizowane.|تم تحديث فعاليتك.|رویداد شما به‌روز شد.|بۆنەکەت نوێکرایەوە.|イベントを更新しました。|你的活动已更新。|आपका कार्यक्रम अपडेट हुआ।
event_owner_save_failed|Échec de l'enregistrement. Vos modifications sont conservées. Réessayez.|No se pudo guardar. Tus cambios siguen aquí. Reinténtalo.|Salvataggio non riuscito. Le modifiche sono ancora qui. Riprova.|Não foi possível guardar. As alterações mantêm-se. Tente novamente.|Opslaan mislukt. Je wijzigingen staan er nog. Probeer opnieuw.|Zapis nie powiódł się. Zmiany są zachowane. Spróbuj ponownie.|تعذّر الحفظ. تغييراتك ما زالت هنا. حاول مجددًا.|ذخیره نشد. تغییرات شما باقی است. دوباره تلاش کنید.|پاشەکەوت نەکرا. گۆڕانکارییەکانت ماون. دووبارە هەوڵ بدە.|保存できませんでした。変更内容は残っています。再試行してください。|保存失败，更改仍保留，请重试。|सहेजा नहीं जा सका। आपके बदलाव मौजूद हैं। फिर प्रयास करें।
event_owner_delete|Supprimer|Eliminar|Elimina|Eliminar|Verwijderen|Usuń|حذف|حذف|سڕینەوە|削除|删除|हटाएँ
event_owner_delete_title|Supprimer l'événement ?|¿Eliminar el evento?|Eliminare l'evento?|Eliminar o evento?|Evenement verwijderen?|Usunąć wydarzenie?|حذف الفعالية؟|رویداد حذف شود؟|بۆنەکە بسڕدرێتەوە؟|イベントを削除しますか？|删除活动？|कार्यक्रम हटाएँ?
event_owner_delete_message|« {title} » sera supprimé définitivement. Cette action est irréversible.|«{title}» se eliminará definitivamente. No se puede deshacer.|«{title}» verrà eliminato definitivamente. Non è possibile annullare.|«{title}» será eliminado permanentemente. Não é possível anular.|'{title}' wordt definitief verwijderd. Dit kan niet ongedaan worden gemaakt.|„{title}” zostanie trwale usunięte. Nie można tego cofnąć.|سيتم حذف «{title}» نهائيًا. لا يمكن التراجع.|«{title}» برای همیشه حذف می‌شود. قابل بازگشت نیست.|«{title}» بۆ هەمیشە دەسڕدرێتەوە. ناگەڕێتەوە.|「{title}」を完全に削除します。元に戻せません。|“{title}”将永久删除，无法撤销。|“{title}” हमेशा के लिए हट जाएगा। इसे वापस नहीं लाया जा सकता।
event_owner_delete_failed|Suppression impossible. Votre événement reste disponible. Réessayez.|No se pudo eliminar. Tu evento sigue disponible. Reinténtalo.|Eliminazione non riuscita. L'evento è ancora disponibile. Riprova.|Não foi possível eliminar. O evento mantém-se disponível. Tente novamente.|Verwijderen mislukt. Je evenement is nog beschikbaar. Probeer opnieuw.|Nie udało się usunąć. Wydarzenie nadal istnieje. Spróbuj ponownie.|تعذّر الحذف. فعاليتك ما زالت متاحة. حاول مجددًا.|حذف نشد. رویداد شما همچنان موجود است. دوباره تلاش کنید.|سڕینەوە سەرکەوتوو نەبوو. بۆنەکەت هێشتا بەردەستە. دووبارە هەوڵ بدە.|削除できませんでした。イベントは残っています。再試行してください。|删除失败，活动仍然存在，请重试。|हटाया नहीं जा सका। कार्यक्रम अभी मौजूद है। फिर प्रयास करें।
event_series_title|Offre récurrente|Propuesta periódica|Proposta ricorrente|Oferta recorrente|Terugkerend aanbod|Oferta cykliczna|عرض متكرر|پیشنهاد دوره‌ای|پێشنیاری دووبارەبووەوە|定期開催の企画|定期活动|नियमित प्रस्ताव
event_series_follow_hint|Suivez cette offre pour être averti dès qu'une nouvelle date est confirmée.|Sigue esta propuesta y te avisaremos cuando se confirme una nueva fecha.|Segui questa proposta: ti avviseremo quando sarà confermata una nuova data.|Siga esta oferta e receberá um aviso quando uma nova data for confirmada.|Volg dit aanbod en ontvang bericht zodra een nieuwe datum is bevestigd.|Obserwuj ofertę, a powiadomimy Cię po potwierdzeniu nowego terminu.|تابع هذا العرض لنُعلمك عند تأكيد موعد جديد.|این پیشنهاد را دنبال کنید تا با تأیید تاریخ جدید به شما اطلاع دهیم.|شوێن ئەم پێشنیارە بکەوە؛ کە بەرواری نوێ پشتڕاستکرایەوە ئاگادارت دەکەینەوە.|フォローすると新しい日程の確定時に通知します。|关注后，新日期确认时会通知你。|इस प्रस्ताव को फ़ॉलो करें; नई तारीख की पुष्टि होने पर हम सूचना देंगे।
event_series_following_hint|Vous suivez cette offre. Vous serez averti des nouvelles dates.|Sigues esta propuesta. Recibirás avisos de nuevas fechas.|Segui questa proposta. Riceverai avvisi sulle nuove date.|Segue esta oferta. Receberá avisos sobre novas datas.|Je volgt dit aanbod en ontvangt bericht over nieuwe data.|Obserwujesz ofertę. Otrzymasz powiadomienia o nowych terminach.|أنت تتابع هذا العرض. ستتلقى إشعارات بالمواعيد الجديدة.|این پیشنهاد را دنبال می‌کنید. از تاریخ‌های جدید باخبر می‌شوید.|شوێن ئەم پێشنیارە دەکەویت. لە بەروارە نوێیەکان ئاگادار دەکرێیتەوە.|この企画をフォロー中です。新しい日程を通知します。|你已关注此活动，将收到新日期通知。|आप इस प्रस्ताव को फ़ॉलो करते हैं। नई तारीखों की सूचना मिलेगी।
event_series_follow|Suivre l'offre|Seguir propuesta|Segui proposta|Seguir oferta|Aanbod volgen|Obserwuj ofertę|متابعة العرض|دنبال کردن پیشنهاد|شوێن پێشنیارەکە بکەوە|企画をフォロー|关注活动|प्रस्ताव फ़ॉलो करें
event_series_unfollow|Ne plus suivre|Dejar de seguir|Non seguire più|Deixar de seguir|Niet meer volgen|Przestań obserwować|إلغاء المتابعة|لغو دنبال کردن|واز لە شوێنکەوتن بهێنە|フォロー解除|取消关注|फ़ॉलो करना बंद करें
event_series_followed|Vous suivez maintenant cette offre.|Ahora sigues esta propuesta.|Ora segui questa proposta.|Agora segue esta oferta.|Je volgt dit aanbod nu.|Teraz obserwujesz tę ofertę.|أنت الآن تتابع هذا العرض.|اکنون این پیشنهاد را دنبال می‌کنید.|ئێستا شوێن ئەم پێشنیارە دەکەویت.|この企画をフォローしました。|已关注此活动。|अब आप इस प्रस्ताव को फ़ॉलो करते हैं।
event_series_unfollowed|Vous ne suivez plus cette offre.|Ya no sigues esta propuesta.|Non segui più questa proposta.|Já não segue esta oferta.|Je volgt dit aanbod niet meer.|Nie obserwujesz już tej oferty.|لم تعد تتابع هذا العرض.|دیگر این پیشنهاد را دنبال نمی‌کنید.|چیتر شوێن ئەم پێشنیارە ناکەویت.|この企画のフォローを解除しました。|已取消关注此活动。|अब आप इस प्रस्ताव को फ़ॉलो नहीं करते।
event_series_sign_in_required|Connectez-vous pour suivre une offre.|Inicia sesión para seguir una propuesta.|Accedi per seguire una proposta.|Inicie sessão para seguir uma oferta.|Log in om een aanbod te volgen.|Zaloguj się, aby obserwować ofertę.|سجّل الدخول لمتابعة عرض.|برای دنبال کردن پیشنهاد وارد شوید.|بۆ شوێنکەوتنی پێشنیارێک بچۆ ژوورەوە.|フォローするにはログインしてください。|请登录后关注活动。|प्रस्ताव फ़ॉलो करने के लिए लॉग इन करें।
event_detail_registered|Vous êtes inscrit !|¡Estás inscrito!|Sei iscritto!|Está inscrito!|Je bent aangemeld!|Jesteś zapisany!|أنت مسجّل!|ثبت‌نام شدید!|تۆمارکراویت!|参加登録済みです。|你已报名！|आप पंजीकृत हैं!
event_detail_open_chat|Ouvrir la discussion|Abrir chat|Apri chat|Abrir conversa|Chat openen|Otwórz czat|فتح المحادثة|باز کردن گفتگو|گفتوگۆ بکەرەوە|チャットを開く|打开聊天|चैट खोलें
event_detail_request_pending|Demande en attente|Solicitud pendiente|Richiesta in attesa|Pedido pendente|Verzoek in afwachting|Prośba oczekuje|الطلب معلق|درخواست در انتظار|داواکاری چاوەڕوانە|申請保留中|申请待处理|अनुरोध लंबित है
event_detail_request_declined|Demande refusée|Solicitud rechazada|Richiesta rifiutata|Pedido recusado|Verzoek afgewezen|Prośba odrzucona|تم رفض الطلب|درخواست رد شد|داواکاری ڕەتکرایەوە|申請が拒否されました|申请已拒绝|अनुरोध अस्वीकार हुआ
event_detail_request_participation|Demander à participer|Solicitar participación|Richiedi partecipazione|Pedir participação|Deelname aanvragen|Poproś o udział|طلب المشاركة|درخواست شرکت|داوای بەشداری بکە|参加を申請|申请参加|भाग लेने का अनुरोध करें
event_detail_age_groups|Tranches d'âge|Grupos de edad|Fasce d'età|Faixas etárias|Leeftijdsgroepen|Grupy wiekowe|الفئات العمرية|گروه‌های سنی|گرووپەکانی تەمەن|年齢層|年龄组|आयु समूह
event_category_sports|Sport|Deporte|Sport|Desporto|Sport|Sport|رياضة|ورزش|وەرزش|スポーツ|运动|खेल
event_category_outdoor|Plein air|Al aire libre|All'aperto|Ao ar livre|Buiten|Na świeżym powietrzu|في الهواء الطلق|فضای باز|لە دەرەوە|屋外|户外|बाहर की गतिविधियाँ
event_category_education|Éducation|Educación|Istruzione|Educação|Educatie|Edukacja|تعليم|آموزش|پەروەردە|教育|教育|शिक्षा
event_category_arts|Arts|Arte|Arte|Artes|Kunst|Sztuka|فنون|هنر|هونەر|芸術|艺术|कला
event_category_social|Rencontre conviviale|Encuentro social|Incontro sociale|Convívio|Gezellig samenzijn|Spotkanie towarzyskie|لقاء اجتماعي|گردهمایی اجتماعی|کۆبوونەوەی کۆمەڵایەتی|交流会|社交聚会|सामाजिक मिलन
event_category_other|Autre|Otro|Altro|Outro|Overig|Inne|أخرى|سایر|هی تر|その他|其他|अन्य
event_age_infant|Bébé (0–1)|Bebé (0–1)|Bebè (0–1)|Bebé (0–1)|Baby (0–1)|Niemowlę (0–1)|رضيع (٠–١)|نوزاد (۰–۱)|کۆرپە (٠–١)|乳児（0～1歳）|婴儿（0–1岁）|शिशु (0–1)
event_age_toddler|Tout-petit (1–3)|Niño pequeño (1–3)|Bimbo piccolo (1–3)|Criança pequena (1–3)|Peuter (1–3)|Maluch (1–3)|طفل صغير (١–٣)|خردسال (۱–۳)|منداڵی بچووک (١–٣)|幼児（1～3歳）|幼儿（1–3岁）|छोटा बच्चा (1–3)
event_age_preschool|Maternelle (3–5)|Preescolar (3–5)|Prescolare (3–5)|Pré-escolar (3–5)|Kleuter (3–5)|Przedszkolak (3–5)|ما قبل المدرسة (٣–٥)|پیش‌دبستانی (۳–۵)|پێش قوتابخانە (٣–٥)|未就学児（3～5歳）|学龄前（3–5岁）|पूर्व-प्राथमिक (3–5)
event_age_elementary|Primaire (6–12)|Primaria (6–12)|Scuola primaria (6–12)|Ensino básico (6–12)|Basisschool (6–12)|Szkoła podstawowa (6–12)|ابتدائي (٦–١٢)|دبستان (۶–۱۲)|سەرەتایی (٦–١٢)|小学生（6～12歳）|小学（6–12岁）|प्राथमिक विद्यालय (6–12)
event_age_teenager|Adolescent (13+)|Adolescente (13+)|Adolescente (13+)|Adolescente (13+)|Tiener (13+)|Nastolatek (13+)|مراهق (١٣+)|نوجوان (۱۳+)|هەرزەکار (١٣+)|中高生（13歳以上）|青少年（13岁以上）|किशोर (13+)
events_near_you|Événements près de vous|Eventos cerca de ti|Eventi vicino a te|Eventos perto de si|Evenementen bij jou in de buurt|Wydarzenia w pobliżu|فعاليات بالقرب منك|رویدادهای نزدیک شما|بۆنەکان لە نزیکت|近くのイベント|附近的活动|आपके पास के कार्यक्रम
event_scan_title|Scanner une affiche et remplir le formulaire|Escanear un cartel y rellenar automáticamente|Scansiona un volantino e compila il modulo|Digitalizar um folheto e preencher o formulário|Flyer scannen en automatisch invullen|Zeskanuj ulotkę i wypełnij formularz|مسح منشور وملء النموذج تلقائيًا|اسکن آگهی و تکمیل خودکار فرم|پۆستەر سکان بکە و فۆڕمەکە پڕ بکەرەوە|チラシを読み取り自動入力|扫描传单并自动填写|पर्चा स्कैन करके फ़ॉर्म अपने आप भरें
event_scan_subtitle|Photographiez une affiche ou collez un texte ; nous remplirons le formulaire.|Fotografía un cartel o pega un texto; rellenaremos el formulario.|Fotografa un volantino o incolla un testo: compileremo il modulo.|Fotografe um folheto ou cole um texto; preencheremos o formulário.|Fotografeer een flyer of plak tekst; wij vullen het formulier in.|Zrób zdjęcie ulotki lub wklej tekst; wypełnimy formularz.|صوّر منشورًا أو الصق نصًا لنملأ النموذج.|از آگهی عکس بگیرید یا متن را بچسبانید تا فرم را پر کنیم.|وێنەی پۆستەر بگرە یان دەق دابنێ؛ فۆڕمەکەت بۆ پڕ دەکەینەوە.|チラシの写真や貼り付けた文章からフォームを入力します。|拍摄传单或粘贴文字，我们将填写表单。|पर्चे की तस्वीर लें या पाठ चिपकाएँ; हम फ़ॉर्म भरेंगे।
event_scan_sheet_title|D'où viennent les informations ?|¿De dónde obtenemos la información?|Da dove prendiamo le informazioni?|De onde obtemos as informações?|Waar halen we de informatie vandaan?|Skąd pobrać informacje?|من أين نأخذ المعلومات؟|اطلاعات را از کجا بگیریم؟|زانیارییەکان لە کوێ وەربگرین؟|情報の取得元は？|从哪里获取信息？|जानकारी कहाँ से लें?
event_scan_sheet_subtitle|Vous pourrez tout modifier ensuite.|Podrás modificarlo todo después.|Potrai modificare tutto dopo.|Pode ajustar tudo depois.|Je kunt alles achteraf aanpassen.|Później możesz wszystko zmienić.|يمكنك تعديل كل شيء لاحقًا.|بعداً می‌توانید همه چیز را تغییر دهید.|دواتر دەتوانیت هەمووی دەستکاری بکەیت.|後からすべて変更できます。|之后可以调整所有内容。|बाद में सब कुछ बदल सकते हैं।
event_scan_camera|Photographier l'affiche|Fotografiar cartel|Fotografa volantino|Fotografar folheto|Flyer fotograferen|Zrób zdjęcie ulotki|تصوير المنشور|عکاسی از آگهی|وێنەی پۆستەر بگرە|チラシを撮影|拍摄传单|पर्चे की तस्वीर लें
event_scan_camera_hint|Ouvrez l'appareil photo et photographiez l'annonce|Abre la cámara y fotografía el anuncio|Apri la fotocamera e fotografa l'avviso|Abra a câmara e fotografe o anúncio|Open de camera en fotografeer de aankondiging|Otwórz aparat i zrób zdjęcie ogłoszenia|افتح الكاميرا وصوّر الإعلان|دوربین را باز کنید و از اعلان عکس بگیرید|کامێرا بکەرەوە و وێنەی ڕاگەیاندنەکە بگرە|カメラで案内を撮影|打开相机拍摄公告|कैमरा खोलकर सूचना की तस्वीर लें
event_scan_gallery|Choisir dans la galerie|Elegir de la galería|Scegli dalla galleria|Escolher da galeria|Kiezen uit de galerij|Wybierz z galerii|اختيار من المعرض|انتخاب از گالری|لە گەلەری هەڵبژێرە|写真から選択|从相册选择|गैलरी से चुनें
event_scan_gallery_hint|Utiliser une image d'affiche enregistrée|Usar una imagen guardada del cartel|Usa un'immagine salvata del volantino|Usar uma imagem guardada do folheto|Een opgeslagen flyerafbeelding gebruiken|Użyj zapisanego zdjęcia ulotki|استخدام صورة منشور محفوظة|استفاده از تصویر ذخیره‌شده آگهی|وێنەی پاشەکەوتکراوی پۆستەر بەکار بهێنە|保存済みのチラシ画像を使用|使用已保存的传单图片|पर्चे की सहेजी हुई तस्वीर इस्तेमाल करें
event_scan_text|Coller un texte|Pegar texto|Incolla testo|Colar texto|Tekst plakken|Wklej tekst|لصق نص|چسباندن متن|دەق دابنێ|文章を貼り付け|粘贴文字|पाठ चिपकाएँ
event_scan_text_hint|Coller une annonce reçue par message ou courriel|Pegar un anuncio de un chat o correo|Incolla un annuncio da chat o email|Colar um anúncio de conversa ou correio|Een aankondiging uit chat of e-mail plakken|Wklej ogłoszenie z czatu lub poczty|لصق إعلان من محادثة أو بريد|چسباندن اعلان از گفتگو یا ایمیل|ڕاگەیاندنێک لە گفتوگۆ یان ئیمەیڵ دابنێ|チャットやメールの案内を貼り付け|粘贴聊天或邮件中的公告|चैट या ईमेल की सूचना चिपकाएँ
event_scan_text_placeholder|Collez ici le texte de l'événement (par ex. depuis WhatsApp)…|Pega aquí el texto del evento (p. ej., de WhatsApp)…|Incolla qui il testo dell'evento (ad es. da WhatsApp)…|Cole aqui o texto do evento (por exemplo, do WhatsApp)…|Plak hier de evenementtekst (bijv. uit WhatsApp)…|Wklej tu tekst wydarzenia (np. z WhatsApp)…|الصق نص الفعالية هنا (مثلًا من واتساب)…|متن رویداد را اینجا بچسبانید (مثلاً از واتساپ)…|دەقی بۆنەکە لێرە دابنێ (بۆ نموونە لە واتساپ)…|イベントの案内文をここに貼り付け（WhatsAppなど）…|在此粘贴活动文字（例如来自WhatsApp）…|कार्यक्रम का पाठ यहाँ चिपकाएँ (जैसे WhatsApp से)…
event_scan_analyze|Analyser|Analizar|Analizza|Analisar|Analyseren|Analizuj|تحليل|تحلیل|شیکردنەوە|解析|分析|विश्लेषण करें
event_scan_filled|Champs remplis :|Campos rellenados:|Campi compilati:|Campos preenchidos:|Ingevuld:|Wypełniono:|تم ملء:|تکمیل شد:|پڕکرایەوە:|入力済み：|已填写：|भरा गया:
event_scan_failed|Rien n'a été reconnu. Essayez une photo plus nette ou saisissez les informations.|No se reconoció nada. Prueba con una foto más clara o introdúcelo manualmente.|Nessun dato riconosciuto. Prova una foto più nitida o inserisci a mano.|Nada foi reconhecido. Tente uma foto mais nítida ou preencha manualmente.|Niets herkend. Probeer een scherpere foto of vul het zelf in.|Nic nie rozpoznano. Spróbuj wyraźniejszego zdjęcia lub wpisz ręcznie.|لم نتعرف على شيء. جرّب صورة أوضح أو أدخل المعلومات يدويًا.|چیزی شناسایی نشد. عکس واضح‌تر بگیرید یا دستی وارد کنید.|هیچ نەناسراوە. وێنەیەکی ڕوونتر تاقی بکەرەوە یان بە دەست بنووسە.|読み取れませんでした。鮮明な写真か手入力をお試しください。|未识别到内容，请使用更清晰的照片或手动填写。|कुछ पहचाना नहीं गया। साफ़ तस्वीर लें या जानकारी स्वयं भरें।
event_scan_price_hint|Prix détecté :|Precio detectado:|Prezzo rilevato:|Preço detetado:|Herkende prijs:|Rozpoznana cena:|السعر المكتشف:|قیمت شناسایی‌شده:|نرخی دۆزراوە:|検出した料金：|识别到的价格：|पहचाना गया मूल्य:
event_scan_field_date|Date|Fecha|Data|Data|Datum|Data|التاريخ|تاریخ|بەروار|日付|日期|तारीख
event_scan_field_time|Heure|Hora|Ora|Hora|Tijd|Godzina|الوقت|زمان|کات|時刻|时间|समय
event_scan_field_category|Catégorie|Categoría|Categoria|Categoria|Categorie|Kategoria|الفئة|دسته‌بندی|پۆل|カテゴリ|类别|श्रेणी
event_scan_field_age|Tranche d'âge|Grupo de edad|Fascia d'età|Faixa etária|Leeftijdsgroep|Grupa wiekowa|الفئة العمرية|گروه سنی|گرووپی تەمەن|年齢層|年龄组|आयु समूह
event_scan_choose_date|Choisir une date|Elegir fecha|Scegli data|Escolher data|Datum kiezen|Wybierz datę|اختيار تاريخ|انتخاب تاریخ|بەروار هەڵبژێرە|日付を選択|选择日期|तारीख चुनें
event_scan_date_required|Confirmer la date (obligatoire)|Confirmar fecha (obligatorio)|Conferma data (obbligatorio)|Confirmar data (obrigatório)|Datum bevestigen (verplicht)|Potwierdź datę (wymagane)|تأكيد التاريخ (مطلوب)|تأیید تاریخ (الزامی)|بەروار پشتڕاست بکەرەوە (پێویستە)|日付を確認（必須）|确认日期（必填）|तारीख की पुष्टि करें (आवश्यक)
event_scan_time_required|Confirmer l'heure (obligatoire)|Confirmar hora (obligatorio)|Conferma ora (obbligatorio)|Confirmar hora (obrigatório)|Tijd bevestigen (verplicht)|Potwierdź godzinę (wymagane)|تأكيد الوقت (مطلوب)|تأیید زمان (الزامی)|کات پشتڕاست بکەرەوە (پێویستە)|時刻を確認（必須）|确认时间（必填）|समय की पुष्टि करें (आवश्यक)
event_scan_datetime_required|Confirmez une occurrence future précise avec une date et une heure.|Confirma una ocasión futura concreta con fecha y hora.|Conferma un appuntamento futuro preciso con data e ora.|Confirme uma ocorrência futura concreta com data e hora.|Bevestig een concrete toekomstige datum en tijd.|Potwierdź konkretny przyszły termin z datą i godziną.|أكّد موعدًا محددًا في المستقبل مع تاريخ ووقت.|یک نوبت مشخص در آینده با تاریخ و زمان تأیید کنید.|بەروار و کاتی دیاریکراوی بۆنەیەکی داهاتوو پشتڕاست بکەرەوە.|具体的な未来の開催日時を確認してください。|请确认未来某次活动的具体日期和时间。|आने वाले किसी निश्चित आयोजन की तारीख और समय की पुष्टि करें।
event_scan_recurring_confirm|Afficher la récurrence aux autres parents|Mostrar la repetición a otros padres|Mostra la cadenza agli altri genitori|Mostrar a repetição aos outros pais|Herhalingsschema tonen aan andere ouders|Pokaż harmonogram powtórzeń innym rodzicom|عرض جدول التكرار للآباء الآخرين|نمایش برنامه تکرار به والدین دیگر|خشتەی دووبارەبوونەوە بە دایک و باوکی تر پیشان بدە|繰り返し予定を他の保護者に表示|向其他家长显示重复安排|दोहराव का समय अन्य माता-पिता को दिखाएँ
event_scan_recurring_explanation|Vérifiez l'affiche. Le rythme figurera dans la description ; aucune date future ni notification ne sera créée automatiquement.|Revisa el cartel. La repetición aparecerá en la descripción; no se crearán fechas futuras ni avisos automáticamente.|Controlla il volantino. La cadenza appare nella descrizione; date future e notifiche non vengono create automaticamente.|Verifique o folheto. A repetição aparece na descrição; não são criadas datas futuras nem notificações automaticamente.|Controleer de flyer. Dit komt in de beschrijving; toekomstige data en meldingen worden niet automatisch aangemaakt.|Sprawdź ulotkę. Harmonogram pojawi się w opisie; przyszłe terminy i powiadomienia nie powstają automatycznie.|تحقّق من المنشور. سيظهر التكرار في الوصف؛ لن تُنشأ مواعيد مستقبلية أو إشعارات تلقائيًا.|آگهی را بررسی کنید. تکرار در توضیحات می‌آید؛ تاریخ‌های آینده و اعلان‌ها خودکار ایجاد نمی‌شوند.|زانیاری پۆستەرەکە بپشکنە. لە وەسف دەردەکەوێت؛ بەرواری داهاتوو و ئاگادارکردنەوە بە خۆکار دروست ناکرێن.|チラシの情報を確認してください。説明に表示されますが、今後の日程や通知は自動作成されません。|请核对传单信息。重复安排将显示在说明中，不会自动创建未来日期或通知。|पर्चे की जानकारी जाँचें। दोहराव विवरण में दिखेगा; भविष्य की तारीखें या सूचनाएँ अपने आप नहीं बनेंगी।
event_ready|L'événement est prêt|El evento está listo|L'evento è pronto|O evento está pronto|Het evenement is klaar|Wydarzenie jest gotowe|الفعالية جاهزة|رویداد آماده است|بۆنەکە ئامادەیە|イベントの準備完了|活动已准备好|कार्यक्रम तैयार है
events_activities_title|Événements et activités|Eventos y actividades|Eventi e attività|Eventos e atividades|Evenementen en activiteiten|Wydarzenia i aktywności|فعاليات وأنشطة|رویدادها و فعالیت‌ها|بۆنە و چالاکییەکان|イベントとアクティビティ|活动与聚会|कार्यक्रम और गतिविधियाँ
events_empty_title|Aucun événement près de vous actuellement|No hay eventos cerca ahora|Nessun evento vicino a te al momento|Sem eventos perto de si agora|Momenteel geen evenementen in de buurt|Obecnie brak wydarzeń w pobliżu|لا توجد فعاليات بالقرب منك الآن|اکنون رویدادی نزدیک شما نیست|ئێستا هیچ بۆنەیەک لە نزیکت نییە|現在近くのイベントはありません|目前附近没有活动|अभी आपके पास कोई कार्यक्रम नहीं
events_empty_subtitle|Aucun événement adapté trouvé. Élargissez le rayon, changez de ville ou revenez plus tard.|No encontramos eventos adecuados. Amplía el radio, cambia de ciudad o vuelve más tarde.|Nessun evento adatto trovato. Amplia il raggio, cambia città o torna più tardi.|Não encontrámos eventos adequados. Aumente o raio, mude de cidade ou volte mais tarde.|Geen passende evenementen gevonden. Vergroot de straal, kies een andere stad of kijk later opnieuw.|Nie znaleziono odpowiednich wydarzeń. Zwiększ promień, zmień miasto lub wróć później.|لم نجد فعاليات مناسبة. وسّع النطاق أو اختر مدينة أخرى أو عد لاحقًا.|رویداد مناسبی پیدا نشد. شعاع را بیشتر کنید، شهر دیگری انتخاب کنید یا بعداً برگردید.|بۆنەی گونجاومان نەدۆزییەوە. بازنەکە فراوان بکە، شارێکی تر هەڵبژێرە یان دواتر بگەڕێوە.|該当するイベントがありません。範囲を広げるか、別の都市や時間でお試しください。|未找到合适活动，请扩大范围、更换城市或稍后再试。|उपयुक्त कार्यक्रम नहीं मिला। दायरा बढ़ाएँ, दूसरा शहर चुनें या बाद में देखें।
event_login_required|Connectez-vous pour créer un événement.|Inicia sesión para crear un evento.|Accedi per creare un evento.|Inicie sessão para criar um evento.|Log in om een evenement aan te maken.|Zaloguj się, aby utworzyć wydarzenie.|سجّل الدخول لإنشاء فعالية.|برای ایجاد رویداد وارد شوید.|بۆ دروستکردنی بۆنە بچۆ ژوورەوە.|イベントを作成するにはログインしてください。|请登录后创建活动。|कार्यक्रम बनाने के लिए लॉग इन करें।
event_select_age_group|Choisissez au moins une tranche d'âge.|Selecciona al menos un grupo de edad.|Seleziona almeno una fascia d'età.|Selecione pelo menos uma faixa etária.|Kies minstens één leeftijdsgroep.|Wybierz co najmniej jedną grupę wiekową.|اختر فئة عمرية واحدة على الأقل.|حداقل یک گروه سنی انتخاب کنید.|لانیکەم گرووپێکی تەمەن هەڵبژێرە.|年齢層を少なくとも一つ選んでください。|请至少选择一个年龄组。|कम से कम एक आयु समूह चुनें।
event_invite_contact|Invitez au moins un contact.|Invita al menos a un contacto.|Invita almeno un contatto.|Convide pelo menos um contacto.|Nodig minstens één contact uit.|Zaproś co najmniej jedną osobę.|ادعُ جهة اتصال واحدة على الأقل.|حداقل یک مخاطب دعوت کنید.|لانیکەم پەیوەندییەک بانگهێشت بکە.|連絡先を少なくとも一人招待してください。|请至少邀请一位联系人。|कम से कम एक संपर्क को आमंत्रित करें।
event_next|Suivant|Siguiente|Avanti|Seguinte|Volgende|Dalej|التالي|بعدی|دواتر|次へ|下一步|अगला
event_is_live|Votre événement est en ligne.|Tu evento ya está publicado.|Il tuo evento è online.|O seu evento está publicado.|Je evenement staat nu online.|Twoje wydarzenie jest już opublikowane.|تم نشر فعاليتك.|رویداد شما منتشر شد.|بۆنەکەت بڵاوکرایەوە.|イベントを公開しました。|你的活动已发布。|आपका कार्यक्रम प्रकाशित हो गया।
event_created_success|Votre événement a été créé.|Tu evento se ha creado correctamente.|Il tuo evento è stato creato.|O seu evento foi criado com sucesso.|Je evenement is aangemaakt.|Twoje wydarzenie zostało utworzone.|تم إنشاء فعاليتك بنجاح.|رویداد شما با موفقیت ایجاد شد.|بۆنەکەت بە سەرکەوتوویی دروستکرا.|イベントを作成しました。|你的活动创建成功。|आपका कार्यक्रम सफलतापूर्वक बनाया गया।
events_free|Gratuit|Gratis|Gratuito|Gratuito|Gratis|Bezpłatne|مجاني|رایگان|بەخۆڕایی|無料|免费|निःशुल्क
events_add_event|Ajouter un événement|Añadir evento|Aggiungi evento|Adicionar evento|Evenement toevoegen|Dodaj wydarzenie|إضافة فعالية|افزودن رویداد|بۆنە زیاد بکە|イベントを追加|添加活动|कार्यक्रम जोड़ें
events_no_nearby|Aucun événement près de vous pour le moment|Aún no hay eventos cerca|Ancora nessun evento vicino a te|Ainda sem eventos perto de si|Nog geen evenementen in de buurt|Jeszcze brak wydarzeń w pobliżu|لا توجد فعاليات قريبة بعد|هنوز رویدادی نزدیک شما نیست|هێشتا بۆنەیەک لە نزیکت نییە|近くのイベントはまだありません|附近暂无活动|अभी आसपास कोई कार्यक्रम नहीं
events_be_first|Soyez le premier ! Ajoutez un événement pour aider d'autres familles.|¡Sé el primero! Añade un evento y ayuda a otras familias.|Sii il primo! Aggiungi un evento e aiuta altre famiglie.|Seja o primeiro! Adicione um evento e ajude outras famílias.|Wees de eerste! Voeg een evenement toe en help andere gezinnen.|Bądź pierwszy! Dodaj wydarzenie i pomóż innym rodzinom.|كن الأول! أضف فعالية وساعد العائلات الأخرى.|اولین نفر باشید! رویدادی اضافه کنید و به خانواده‌های دیگر کمک کنید.|یەکەم کەس بە! بۆنەیەک زیاد بکە و یارمەتی خێزانەکانی تر بدە.|最初の一人に！イベントを追加して他の家族を助けましょう。|成为第一位！添加活动，帮助其他家庭。|पहले बनें! कार्यक्रम जोड़कर अन्य परिवारों की मदद करें।
`;
const aliases = {
  event_detail_join_sign_in_required: 'event_detail_sign_in_required',
  event_age_mixed: 'events_age_mixed',
  event_scan_button: 'event_scan_camera',
  event_scan_field_title: 'event_owner_title',
  event_scan_field_description: 'event_detail_description',
  event_scan_field_location: 'event_owner_location',
  events_activities: 'events_activities_title',
  events_add_event_short: 'events_add_event',
};
const additions = {
  de: {event_host: 'Gastgeber', event_shared_by: 'Geteilt von'},
  en: {event_host: 'Host', event_shared_by: 'Shared by'},
  tr: {event_host: 'Ev sahibi', event_shared_by: 'Paylaşan'},
  ku: {event_host: 'Mêvandar', event_shared_by: 'Ji aliyê ve hat parvekirin'},
};
for (const code of codes) additions[code] = {};
for (const row of rows.trim().split('\n')) {
  const [key, ...values] = row.split('|');
  if (values.length !== codes.length) throw new Error(`${key}: ${values.length} values`);
  codes.forEach((code, index) => { additions[code][key] = values[index]; });
}
for (const code of codes) {
  for (const [alias, key] of Object.entries(aliases)) {
    if (!additions[code][key]) throw new Error(`Missing alias source ${code}:${key}`);
    additions[code][alias] = additions[code][key];
  }
}
const original = fs.readFileSync(file, 'utf8').replace(/^    '([a-z]+)': \{\n\n/gm,
  (header, code) => additions[code] ? header : header.slice(0, -1));
const quote = value => "'" + value.replaceAll('\\', '\\\\').replaceAll("'", "\\'").replaceAll('\n', '\\n') + "'";
let count = 0;
const updated = original.replace(/^    '([a-z]+)': \{([\s\S]*?)(?=^    '[a-z]+': \{|^  };)/gm, (block, code, body) => {
  const entries = Object.entries(additions[code] ?? {}).filter(([key]) => !body.includes(quote(key) + ':'));
  if (entries.length === 0) return block;
  count += entries.length;
  return block.replace(`    '${code}': {`, `    '${code}': {\n` + entries.map(([key, value]) => `      ${quote(key)}: ${quote(value)},`).join('\n'));
});
fs.writeFileSync(file, updated);
console.log(`Added ${count} missing event translations only.`);